### ISSUE TITLE
复制cookie无效

### ISSUE THREAD

**Issue by ZemonVunter** [qiaoxingxing/zhihu-column-downloader#1]
PS F:\知乎工具\zhihu-column-downloader> python column_downloader.py https://www.zhihu.com/xen/market/remix/paid_column/1264573589136506880
arg1: https://www.zhihu.com/xen/market/remix/paid_column/1264573589136506880
id:  1264573589136506880
name:  奇说妙语 2：看完了结尾，又怀疑开头的 20 个故事--方舟 等
Traceback (most recent call last):
  File "column_downloader.py", line 376, in <module>
    download_main()
  File "column_downloader.py", line 365, in download_main
    download_url(url,False)
  File "column_downloader.py", line 324, in download_url
    download(id, name)
  File "column_downloader.py", line 224, in download
    courses_data = get_courses_data(id)
  File "column_downloader.py", line 60, in get_courses_data
    raise RuntimeError("not login")
RuntimeError: not login

**Comment by zhanwangls** [comment]
> PS F:\知乎工具\zhihu-column-downloader> python column_downloader.py https://www.zhihu.com/xen/market/remix/paid_column/1264573589136506880
> arg1: https://www.zhihu.com/xen/market/remix/paid_column/1264573589136506880
> id: 1264573589136506880
> name: 奇说妙语 2：看完了结尾，又怀疑开头的 20 个故事--方舟 等
> Traceback (most recent call last):
> File "column_downloader.py", line 376, in
> download_main()
> File "column_downloader.py", line 365, in download_main
> download_url(url,False)
> File "column_downloader.py", line 324, in download_url
> download(id, name)
> File "column_downloader.py", line 224, in download
> courses_data = get_courses_data(id)
> File "column_downloader.py", line 60, in get_courses_data
> raise RuntimeError("not login")
> RuntimeError: not login

可以看出作者是用https://www.zhihu.com/api/v4/me 这个链接验证token的。
所以
1. 在网页上登陆知乎
2. 浏览器打开 https://www.zhihu.com/api/v4/me
3. F12打开DevTools
4. 查看request header ，找到cookie
5. 复制cookie值到cookie.txt文件
经过个人验证，可以下载。

**Comment by zhanwangls** [comment]
> PS F:\知乎工具\zhihu-column-downloader> python column_downloader.py https://www.zhihu.com/xen/market/remix/paid_column/1264573589136506880
> arg1: https://www.zhihu.com/xen/market/remix/paid_column/1264573589136506880
> id: 1264573589136506880
> name: 奇说妙语 2：看完了结尾，又怀疑开头的 20 个故事--方舟 等
> Traceback (most recent call last):
> File "column_downloader.py", line 376, in
> download_main()
> File "column_downloader.py", line 365, in download_main
> download_url(url,False)
> File "column_downloader.py", line 324, in download_url
> download(id, name)
> File "column_downloader.py", line 224, in download
> courses_data = get_courses_data(id)
> File "column_downloader.py", line 60, in get_courses_data
> raise RuntimeError("not login")
> RuntimeError: not login

可以看出作者是用https://www.zhihu.com/api/v4/me 这个链接验证token的。
所以

1. 在网页上登陆知乎
2. 浏览器打开 https://www.zhihu.com/api/v4/me
3. F12打开DevTools
4. 查看request header ，找到cookie
5. 复制cookie值到cookie.txt文件

经过个人验证，可以下载。
